//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class TotalHREntities : DbContext
    {
        public TotalHREntities()
            : base("name=TotalHREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Company> Companies { get; set; }
        public DbSet<Glossary> Glossaries { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<CompanyFeature> CompanyFeatures { get; set; }
        public DbSet<Feature> Features { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<Calendar> Calendars { get; set; }
        public DbSet<CalendarEvent> CalendarEvents { get; set; }
        public DbSet<CalendarEventInvite> CalendarEventInvites { get; set; }
        public DbSet<CalendarEventReminder> CalendarEventReminders { get; set; }
        public DbSet<Department> Departments { get; set; }

        public virtual ObjectResult<Nullable<int>> GetUserProfileIds(Nullable<int> userid)
        {
            //var useridParameter = 
            ObjectParameter[] lst = new ObjectParameter[] { };
            lst[0] = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetUserProfileIds", lst);
        }

        public virtual ObjectResult<GetUserProfiles_Result> GetUserProfiles(Nullable<int> userid)
        {
            ObjectParameter[] lst = new ObjectParameter[] { };
            lst[0] = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserProfiles_Result>("GetUserProfiles", lst);
        }

        public virtual ObjectResult<Nullable<int>> GetUserRoleIds(Nullable<int> userid)
        {
            ObjectParameter[] lst = new ObjectParameter[] { };
            lst[0] = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetUserRoleIds", lst);
        }

        public virtual ObjectResult<GetUserRoles_Result> GetUserRoles(Nullable<int> userid)
        {
            ObjectParameter[] lst = new ObjectParameter[] { };
            lst[0] = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserRoles_Result>("GetUserRoles", lst);
        }
    }
}
