//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsenceReply
    {
        public int Id { get; set; }
        public int AbsenceId { get; set; }
        public int MangerId { get; set; }
        public System.DateTime DateOfReply { get; set; }
        public bool Approved { get; set; }
        public Nullable<int> MessageId { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual User User { get; set; }
    }
}
