//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CalendarEvent()
        {
            this.CalendarAssociations = new HashSet<CalendarAssociation>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastModifed { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public System.DateTime StartOfEvent { get; set; }
        public System.DateTime EndOfEvent { get; set; }
        public string Location { get; set; }
        public int CalendarId { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalendarAssociation> CalendarAssociations { get; set; }
    }
}
