//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomUser
    {
        public int UserId { get; set; }
        public int ChatRoomId { get; set; }
        public string NickName { get; set; }
        public System.DateTime LoggedOnTime { get; set; }
        public Nullable<System.DateTime> LastPing { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        public virtual ChatRoom ChatRoom { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
