//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMessage
    {
        public int Id { get; set; }
        public int ChatUserid { get; set; }
        public int ChatRoomId { get; set; }
        public System.DateTime MessageDate { get; set; }
        public string MessageContent { get; set; }
    
        public virtual ChatMessage ChatMessage1 { get; set; }
        public virtual ChatMessage ChatMessage2 { get; set; }
    }
}
