//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDocumentPermission
    {
        public int DocumentId { get; set; }
        public int PermissionTypeId { get; set; }
        public int ObjectId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual CompanyDocument CompanyDocument { get; set; }
        public virtual User User { get; set; }
    }
}
