//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDocumentDownload
    {
        public int id { get; set; }
        public int DocumentId { get; set; }
        public int UserId { get; set; }
        public System.DateTime DownloadDate { get; set; }
    }
}
