//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractTemplateSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractTemplateSection()
        {
            this.CTemplateSectionLinks = new HashSet<CTemplateSectionLink>();
            this.CTSectionFieldLinks = new HashSet<CTSectionFieldLink>();
        }
    
        public int id { get; set; }
        public string SectionName { get; set; }
        public string Heading { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public int TemplateId { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTemplateSectionLink> CTemplateSectionLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSectionFieldLink> CTSectionFieldLinks { get; set; }
    }
}
