//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractFormFieldValue
    {
        public int FormFieldid { get; set; }
        public int Userid { get; set; }
        public string Value { get; set; }
        public Nullable<int> IntValue { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Lastupdated { get; set; }
        public Nullable<int> LastupdatedBy { get; set; }
    }
}
