//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSectionFieldLink
    {
        public int TemplateSectionId { get; set; }
        public int FormFieldId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ContractTemplateSection ContractTemplateSection { get; set; }
        public virtual FormField FormField { get; set; }
        public virtual User User { get; set; }
    }
}
