//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventToSchedule
    {
        public int id { get; set; }
        public int EventId { get; set; }
        public int CompanyId { get; set; }
        public string RecipientListName { get; set; }
        public string Description { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    }
}
