//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormFieldJSon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormFieldJSon()
        {
            this.FormFieldValidationRules = new HashSet<FormFieldValidationRule>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string PlaceHolderText { get; set; }
        public string ToolTip { get; set; }
        public string InitialValue { get; set; }
        public int TypeId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public bool obsolete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormFieldValidationRule> FormFieldValidationRules { get; set; }
    }
}
