//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CompanyDocuments = new HashSet<CompanyDocument>();
            this.CompanyFolders = new HashSet<CompanyFolder>();
            this.CompanyDocumentPermissions = new HashSet<CompanyDocumentPermission>();
            this.ContractTemplates = new HashSet<ContractTemplate>();
            this.CTSectionFieldLinks = new HashSet<CTSectionFieldLink>();
            this.UserContracts = new HashSet<UserContract>();
            this.UserContracts1 = new HashSet<UserContract>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.UserRoles = new HashSet<UserRole>();
            this.Profiles = new HashSet<Profile>();
            this.Profiles1 = new HashSet<Profile>();
        }
    
        public int id { get; set; }
        public int GenderId { get; set; }
        public string firstname { get; set; }
        public string othernames { get; set; }
        public string surname { get; set; }
        public int title { get; set; }
        public string othertitle { get; set; }
        public string username { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Town { get; set; }
        public string stateorcounty { get; set; }
        public string PostCode { get; set; }
        public int countryId { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime created { get; set; }
        public int createdby { get; set; }
        public Nullable<System.DateTime> lastvisit { get; set; }
        public int novisits { get; set; }
        public bool active { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<int> lastupdatedby { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public int typeid { get; set; }
        public System.Guid userguid { get; set; }
        public int preferedlanguageid { get; set; }
        public bool tersmaccepted { get; set; }
        public string activationcode { get; set; }
        public string chosenculture { get; set; }
        public int departmentid { get; set; }
    
        public virtual ICollection<CompanyDocument> CompanyDocuments { get; set; }
        public virtual ICollection<CompanyFolder> CompanyFolders { get; set; }
        public virtual ICollection<CompanyDocumentPermission> CompanyDocumentPermissions { get; set; }
        public virtual ICollection<ContractTemplate> ContractTemplates { get; set; }
        public virtual ICollection<CTSectionFieldLink> CTSectionFieldLinks { get; set; }
        public virtual ICollection<UserContract> UserContracts { get; set; }
        public virtual ICollection<UserContract> UserContracts1 { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Profile> Profiles1 { get; set; }
    }
}
