//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserContract
    {
        public int id { get; set; }
        public int Userid { get; set; }
        public int TemplateId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Lastupdated { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public int Views { get; set; }
        public Nullable<System.DateTime> LastViewed { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
