//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.data.TimeRecording
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledNotification
    {
        public int Id { get; set; }
        public int GenericNotificationlTypeId { get; set; }
        public int NotificationTypeId { get; set; }
        public int ObjectId { get; set; }
        public string MessageBody { get; set; }
        public string MessageTitle { get; set; }
        public int RecipientListid { get; set; }
        public System.DateTime ScheduledSendDate { get; set; }
        public int StatusId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string SenderName { get; set; }
        public string SenderEmail { get; set; }
    }
}
