//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Absence {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Absence() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Absence", typeof(Absence).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To is required!.
        /// </summary>
        public static string Error_EndDate_Rq {
            get {
                return ResourceManager.GetString("Error_EndDate_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From is required!.
        /// </summary>
        public static string Error_StarDate_Rq {
            get {
                return ResourceManager.GetString("Error_StarDate_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence type is required!.
        /// </summary>
        public static string Error_Type_Rq {
            get {
                return ResourceManager.GetString("Error_Type_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Creation.
        /// </summary>
        public static string V_Absence_Creation {
            get {
                return ResourceManager.GetString("V_Absence_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Details.
        /// </summary>
        public static string V_Absence_Details {
            get {
                return ResourceManager.GetString("V_Absence_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string V_Absence_Duration_In_Days {
            get {
                return ResourceManager.GetString("V_Absence_Duration_In_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Type.
        /// </summary>
        public static string V_Absence_Type {
            get {
                return ResourceManager.GetString("V_Absence_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Year.
        /// </summary>
        public static string V_Absence_Year {
            get {
                return ResourceManager.GetString("V_Absence_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absences.
        /// </summary>
        public static string V_Absences {
            get {
                return ResourceManager.GetString("V_Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absences List.
        /// </summary>
        public static string V_Absences_List {
            get {
                return ResourceManager.GetString("V_Absences_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string V_Create {
            get {
                return ResourceManager.GetString("V_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Absence.
        /// </summary>
        public static string V_Create_Absence {
            get {
                return ResourceManager.GetString("V_Create_Absence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string V_Duration {
            get {
                return ResourceManager.GetString("V_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string V_End_Date {
            get {
                return ResourceManager.GetString("V_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Leave Summary.
        /// </summary>
        public static string V_Holiday_Summary {
            get {
                return ResourceManager.GetString("V_Holiday_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Saturday.
        /// </summary>
        public static string V_Include_Saturday {
            get {
                return ResourceManager.GetString("V_Include_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Sunday.
        /// </summary>
        public static string V_Include_Sunday {
            get {
                return ResourceManager.GetString("V_Include_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no absence found on the system for you!.
        /// </summary>
        public static string V_No_Absence_Found {
            get {
                return ResourceManager.GetString("V_No_Absence_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Absences.
        /// </summary>
        public static string V_Other_Absences {
            get {
                return ResourceManager.GetString("V_Other_Absences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string V_Reason {
            get {
                return ResourceManager.GetString("V_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string V_Select {
            get {
                return ResourceManager.GetString("V_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string V_StartDate {
            get {
                return ResourceManager.GetString("V_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string V_Status {
            get {
                return ResourceManager.GetString("V_Status", resourceCulture);
            }
        }
    }
}
