//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string btn_Loggout {
            get {
                return ResourceManager.GetString("btn_Loggout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully created the employee {0}. &lt;br/&gt; You will also need to assign some profiles to this employee as no user can access the system without profiles. Select one of the options below to continue..
        /// </summary>
        public static string MSG_User_Created {
            get {
                return ResourceManager.GetString("MSG_User_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, &lt;br/&gt; Welcome to your account. &lt;br/&gt;Please choose an option to start..
        /// </summary>
        public static string MSG_Welcome {
            get {
                return ResourceManager.GetString("MSG_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendars.
        /// </summary>
        public static string tt_My_Calendars {
            get {
                return ResourceManager.GetString("tt_My_Calendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Documents.
        /// </summary>
        public static string tt_My_Documents {
            get {
                return ResourceManager.GetString("tt_My_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        public static string tt_Personal_Details {
            get {
                return ResourceManager.GetString("tt_Personal_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendars.
        /// </summary>
        public static string V_Calendars {
            get {
                return ResourceManager.GetString("V_Calendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string V_Department {
            get {
                return ResourceManager.GetString("V_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string V_Documents {
            get {
                return ResourceManager.GetString("V_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string V_Email {
            get {
                return ResourceManager.GetString("V_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string V_Email1 {
            get {
                return ResourceManager.GetString("V_Email1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string V_Firstname {
            get {
                return ResourceManager.GetString("V_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string V_Gender {
            get {
                return ResourceManager.GetString("V_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Visit.
        /// </summary>
        public static string V_LastVisit {
            get {
                return ResourceManager.GetString("V_LastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string V_Mobile {
            get {
                return ResourceManager.GetString("V_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Visits.
        /// </summary>
        public static string V_No_Visits {
            get {
                return ResourceManager.GetString("V_No_Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Names.
        /// </summary>
        public static string V_Other_Names {
            get {
                return ResourceManager.GetString("V_Other_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string V_Phone {
            get {
                return ResourceManager.GetString("V_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile View.
        /// </summary>
        public static string V_Profile_View {
            get {
                return ResourceManager.GetString("V_Profile_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string V_Surname {
            get {
                return ResourceManager.GetString("V_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string V_Title {
            get {
                return ResourceManager.GetString("V_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Created.
        /// </summary>
        public static string V_User_Created {
            get {
                return ResourceManager.GetString("V_User_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string V_User_FullName {
            get {
                return ResourceManager.GetString("V_User_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string V_UserId {
            get {
                return ResourceManager.GetString("V_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string V_UserName {
            get {
                return ResourceManager.GetString("V_UserName", resourceCulture);
            }
        }
    }
}
