//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AdminGeneric {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminGeneric() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.AdminGeneric", typeof(AdminGeneric).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select an item from the source list before moving it..
        /// </summary>
        public static string Error_No_Item_Selected {
            get {
                return ResourceManager.GetString("Error_No_Item_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no user has been assigned this profile..
        /// </summary>
        public static string Error_No_User_Under_Profile {
            get {
                return ResourceManager.GetString("Error_No_User_Under_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Home.
        /// </summary>
        public static string V_Admin_Home_Title {
            get {
                return ResourceManager.GetString("V_Admin_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Profiles.
        /// </summary>
        public static string V_All_Profiles {
            get {
                return ResourceManager.GetString("V_All_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Roles.
        /// </summary>
        public static string V_All_Roles {
            get {
                return ResourceManager.GetString("V_All_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string V_Assign {
            get {
                return ResourceManager.GetString("V_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign All.
        /// </summary>
        public static string V_Assign_All {
            get {
                return ResourceManager.GetString("V_Assign_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string V_Back_To_List {
            get {
                return ResourceManager.GetString("V_Back_To_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string V_Created_By {
            get {
                return ResourceManager.GetString("V_Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string V_Created_On {
            get {
                return ResourceManager.GetString("V_Created_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string V_Department {
            get {
                return ResourceManager.GetString("V_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string V_Description {
            get {
                return ResourceManager.GetString("V_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Profiles.
        /// </summary>
        public static string V_Existing_Profiles {
            get {
                return ResourceManager.GetString("V_Existing_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string V_Home {
            get {
                return ResourceManager.GetString("V_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string V_Last_Modified {
            get {
                return ResourceManager.GetString("V_Last_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified By.
        /// </summary>
        public static string V_Last_Modified_By {
            get {
                return ResourceManager.GetString("V_Last_Modified_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing list of all available profiles..
        /// </summary>
        public static string V_List_Of_Profiles_Intro {
            get {
                return ResourceManager.GetString("V_List_Of_Profiles_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing list of all available roles..
        /// </summary>
        public static string V_List_Of_Roles_Intro {
            get {
                return ResourceManager.GetString("V_List_Of_Roles_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See below a list of users for your company. Use the search to find specific users..
        /// </summary>
        public static string V_List_Of_Users_Intro {
            get {
                return ResourceManager.GetString("V_List_Of_Users_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User Profiles.
        /// </summary>
        public static string V_Manage_Profiles {
            get {
                return ResourceManager.GetString("V_Manage_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        public static string V_Manage_Roles {
            get {
                return ResourceManager.GetString("V_Manage_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Details.
        /// </summary>
        public static string V_More_Details {
            get {
                return ResourceManager.GetString("V_More_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string V_Name {
            get {
                return ResourceManager.GetString("V_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile List.
        /// </summary>
        public static string V_Profile_List {
            get {
                return ResourceManager.GetString("V_Profile_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Management.
        /// </summary>
        public static string V_Profile_Management {
            get {
                return ResourceManager.GetString("V_Profile_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List By Profile.
        /// </summary>
        public static string V_Profile_Management_UserList {
            get {
                return ResourceManager.GetString("V_Profile_Management_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string V_Remove {
            get {
                return ResourceManager.GetString("V_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string V_Remove_All {
            get {
                return ResourceManager.GetString("V_Remove_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Roles.
        /// </summary>
        public static string V_Role_List {
            get {
                return ResourceManager.GetString("V_Role_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        public static string V_Role_Management {
            get {
                return ResourceManager.GetString("V_Role_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List By Role.
        /// </summary>
        public static string V_Role_Management_UserList {
            get {
                return ResourceManager.GetString("V_Role_Management_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string V_Save {
            get {
                return ResourceManager.GetString("V_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string V_Search_ByName {
            get {
                return ResourceManager.GetString("V_Search_ByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial Address.
        /// </summary>
        public static string V_Search_Partial_Address {
            get {
                return ResourceManager.GetString("V_Search_Partial_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/County.
        /// </summary>
        public static string V_State_or_County {
            get {
                return ResourceManager.GetString("V_State_or_County", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Town.
        /// </summary>
        public static string V_Town {
            get {
                return ResourceManager.GetString("V_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string V_User_Id {
            get {
                return ResourceManager.GetString("V_User_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users in role &quot;{0}&quot;.
        /// </summary>
        public static string V_User_In_Role_X {
            get {
                return ResourceManager.GetString("V_User_In_Role_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) List.
        /// </summary>
        public static string V_User_List {
            get {
                return ResourceManager.GetString("V_User_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string V_User_Management {
            get {
                return ResourceManager.GetString("V_User_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string V_User_Management_Details {
            get {
                return ResourceManager.GetString("V_User_Management_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Management.
        /// </summary>
        public static string V_User_Profile_Management {
            get {
                return ResourceManager.GetString("V_User_Profile_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Assigned Profiles.
        /// </summary>
        public static string V_User_Profiles {
            get {
                return ResourceManager.GetString("V_User_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Management.
        /// </summary>
        public static string V_User_Role_Management {
            get {
                return ResourceManager.GetString("V_User_Role_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Assigned Roles.
        /// </summary>
        public static string V_User_Roles {
            get {
                return ResourceManager.GetString("V_User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Search.
        /// </summary>
        public static string V_User_Search {
            get {
                return ResourceManager.GetString("V_User_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string V_User_Type {
            get {
                return ResourceManager.GetString("V_User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string V_Users {
            get {
                return ResourceManager.GetString("V_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users who have been assigned profile: {0}.
        /// </summary>
        public static string V_Users_In_Profile_X {
            get {
                return ResourceManager.GetString("V_Users_In_Profile_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Users.
        /// </summary>
        public static string V_View_Users {
            get {
                return ResourceManager.GetString("V_View_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are view profiles related to user &quot;{0}&quot;..
        /// </summary>
        public static string V_You_Viewing_USerProfile_X {
            get {
                return ResourceManager.GetString("V_You_Viewing_USerProfile_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are view roles assigned to user &quot;{0}&quot;..
        /// </summary>
        public static string V_You_Viewing_USerRole_X {
            get {
                return ResourceManager.GetString("V_You_Viewing_USerRole_X", resourceCulture);
            }
        }
    }
}
