//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btn_SelectDepartment {
            get {
                return ResourceManager.GetString("btn_SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btn_SelectUser {
            get {
                return ResourceManager.GetString("btn_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but the details you provided were not found. Please contact our admin for more details..
        /// </summary>
        public static string Error_Account_Activation_Failed {
            get {
                return ResourceManager.GetString("Error_Account_Activation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br/&gt;&lt;br/&gt; Congratulations! You have just become a full member of TotalHR. &lt;br/&gt;&lt;br/&gt; You can now login at any time into your account and select the features you want and customize your account. For more details on this, please visit our help section..
        /// </summary>
        public static string MSG_Account_Activation_Welcome {
            get {
                return ResourceManager.GetString("MSG_Account_Activation_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br/&gt;Thank you for registering with us. You will receive an email shortly at the following email address {1}. &lt;br/&gt; Please follow instructions on your email to complete your registration. &lt;br/&gt; &lt;br/&gt;Regards,&lt;br/&gt; &lt;br/&gt;{2}.
        /// </summary>
        public static string MSG_Welcome_NewUser {
            get {
                return ResourceManager.GetString("MSG_Welcome_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string Page_TT_Account_Activation {
            get {
                return ResourceManager.GetString("Page_TT_Account_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Account Activation.
        /// </summary>
        public static string Page_TT_Account_Activation_Header {
            get {
                return ResourceManager.GetString("Page_TT_Account_Activation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account - Home.
        /// </summary>
        public static string Page_TT_Account_Home {
            get {
                return ResourceManager.GetString("Page_TT_Account_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Event Add.
        /// </summary>
        public static string Page_TT_Calendar_Event_Add {
            get {
                return ResourceManager.GetString("Page_TT_Calendar_Event_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Event Edit.
        /// </summary>
        public static string Page_TT_Calendar_Event_Edit {
            get {
                return ResourceManager.GetString("Page_TT_Calendar_Event_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reminder.
        /// </summary>
        public static string Page_TT_ForgotPassword {
            get {
                return ResourceManager.GetString("Page_TT_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Account - Home.
        /// </summary>
        public static string Page_TT_Header_Account_Home {
            get {
                return ResourceManager.GetString("Page_TT_Header_Account_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Password Reminder.
        /// </summary>
        public static string Page_TT_Header_Forgot_Password {
            get {
                return ResourceManager.GetString("Page_TT_Header_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Login.
        /// </summary>
        public static string Page_TT_Header_Login {
            get {
                return ResourceManager.GetString("Page_TT_Header_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Registration.
        /// </summary>
        public static string Page_TT_Header_Registration {
            get {
                return ResourceManager.GetString("Page_TT_Header_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Welcome.
        /// </summary>
        public static string Page_TT_Header_Welcome {
            get {
                return ResourceManager.GetString("Page_TT_Header_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Page_TT_Login {
            get {
                return ResourceManager.GetString("Page_TT_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Page_TT_Registration {
            get {
                return ResourceManager.GetString("Page_TT_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Page_TT_Welcome {
            get {
                return ResourceManager.GetString("Page_TT_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TotalHR Team.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string V_Add {
            get {
                return ResourceManager.GetString("V_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string V_Before {
            get {
                return ResourceManager.GetString("V_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string V_Hide {
            get {
                return ResourceManager.GetString("V_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string V_Password_Reminder {
            get {
                return ResourceManager.GetString("V_Password_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string V_Set {
            get {
                return ResourceManager.GetString("V_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string V_Show {
            get {
                return ResourceManager.GetString("V_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string V_Until {
            get {
                return ResourceManager.GetString("V_Until", resourceCulture);
            }
        }
    }
}
