//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btn_SelectDepartment {
            get {
                return ResourceManager.GetString("btn_SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string btn_SelectUser {
            get {
                return ResourceManager.GetString("btn_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but the details you provided were not found. Please contact our admin for more details..
        /// </summary>
        public static string Error_Account_Activation_Failed {
            get {
                return ResourceManager.GetString("Error_Account_Activation_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br/&gt;&lt;br/&gt; Congratulations! You have just become a full member of TotalHR. &lt;br/&gt;&lt;br/&gt; You can now login at any time into your account and select the features you want and customize your account. For more details on this, please visit our help section..
        /// </summary>
        public static string MSG_Account_Activation_Welcome {
            get {
                return ResourceManager.GetString("MSG_Account_Activation_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},&lt;br/&gt;Thank you for registering with us. You will receive an email shortly at the following email address {1}. &lt;br/&gt; Please follow instructions on your email to complete your registration. &lt;br/&gt; &lt;br/&gt;Regards,&lt;br/&gt; &lt;br/&gt;{2}.
        /// </summary>
        public static string MSG_Welcome_NewUser {
            get {
                return ResourceManager.GetString("MSG_Welcome_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string Page_TT_Account_Activation {
            get {
                return ResourceManager.GetString("Page_TT_Account_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Account Activation.
        /// </summary>
        public static string Page_TT_Account_Activation_Header {
            get {
                return ResourceManager.GetString("Page_TT_Account_Activation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account - Home.
        /// </summary>
        public static string Page_TT_Account_Home {
            get {
                return ResourceManager.GetString("Page_TT_Account_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Event Add.
        /// </summary>
        public static string Page_TT_Calendar_Event_Add {
            get {
                return ResourceManager.GetString("Page_TT_Calendar_Event_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Event Edit.
        /// </summary>
        public static string Page_TT_Calendar_Event_Edit {
            get {
                return ResourceManager.GetString("Page_TT_Calendar_Event_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reminder.
        /// </summary>
        public static string Page_TT_ForgotPassword {
            get {
                return ResourceManager.GetString("Page_TT_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Account - Home.
        /// </summary>
        public static string Page_TT_Header_Account_Home {
            get {
                return ResourceManager.GetString("Page_TT_Header_Account_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Password Reminder.
        /// </summary>
        public static string Page_TT_Header_Forgot_Password {
            get {
                return ResourceManager.GetString("Page_TT_Header_Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Login.
        /// </summary>
        public static string Page_TT_Header_Login {
            get {
                return ResourceManager.GetString("Page_TT_Header_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Registration.
        /// </summary>
        public static string Page_TT_Header_Registration {
            get {
                return ResourceManager.GetString("Page_TT_Header_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalHR - Welcome.
        /// </summary>
        public static string Page_TT_Header_Welcome {
            get {
                return ResourceManager.GetString("Page_TT_Header_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Page_TT_Login {
            get {
                return ResourceManager.GetString("Page_TT_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Page_TT_Registration {
            get {
                return ResourceManager.GetString("Page_TT_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Page_TT_Welcome {
            get {
                return ResourceManager.GetString("Page_TT_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The TotalHR Team.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string V_Add {
            get {
                return ResourceManager.GetString("V_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string V_Before {
            get {
                return ResourceManager.GetString("V_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string V_Cancel {
            get {
                return ResourceManager.GetString("V_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not find your details!.
        /// </summary>
        public static string V_Chat_Cant_Add_Message {
            get {
                return ResourceManager.GetString("V_Chat_Cant_Add_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering chat room &apos;{0}&apos;.
        /// </summary>
        public static string V_Chat_Entering_Room {
            get {
                return ResourceManager.GetString("V_Chat_Entering_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your chat nickname.
        /// </summary>
        public static string V_Chat_Nickname {
            get {
                return ResourceManager.GetString("V_Chat_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a nickname or simply click enter in this case your username will appear in chatroom..
        /// </summary>
        public static string V_Chat_Nickname_Intro {
            get {
                return ResourceManager.GetString("V_Chat_Nickname_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but there is no chat room available. You can create one by using the button below..
        /// </summary>
        public static string V_Chat_NoRooms {
            get {
                return ResourceManager.GetString("V_Chat_NoRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last refreshed at {0}.
        /// </summary>
        public static string V_Chat_Refreshed_At {
            get {
                return ResourceManager.GetString("V_Chat_Refreshed_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Registration.
        /// </summary>
        public static string V_Chat_Registration {
            get {
                return ResourceManager.GetString("V_Chat_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Room Creation.
        /// </summary>
        public static string V_Chat_Room_Create {
            get {
                return ResourceManager.GetString("V_Chat_Room_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of chat rooms.
        /// </summary>
        public static string V_Chat_Room_List {
            get {
                return ResourceManager.GetString("V_Chat_Room_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Chatroom.
        /// </summary>
        public static string V_Chat_Room_New {
            get {
                return ResourceManager.GetString("V_Chat_Room_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Rooms.
        /// </summary>
        public static string V_Chat_Rooms {
            get {
                return ResourceManager.GetString("V_Chat_Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string V_Chat_Send {
            get {
                return ResourceManager.GetString("V_Chat_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chat server started at {0}.
        /// </summary>
        public static string V_Chat_Server_Started_At {
            get {
                return ResourceManager.GetString("V_Chat_Server_Started_At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a message here....
        /// </summary>
        public static string V_Chat_Type_Message {
            get {
                return ResourceManager.GetString("V_Chat_Type_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; left the room..
        /// </summary>
        public static string V_Chat_User_X_LoggedOff {
            get {
                return ResourceManager.GetString("V_Chat_User_X_LoggedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; joined the chat..
        /// </summary>
        public static string V_Chat_User_X_LoggedOn {
            get {
                return ResourceManager.GetString("V_Chat_User_X_LoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname.
        /// </summary>
        public static string V_Chat_Your_Nickname {
            get {
                return ResourceManager.GetString("V_Chat_Your_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string V_ChatRoom_Description {
            get {
                return ResourceManager.GetString("V_ChatRoom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Room Details.
        /// </summary>
        public static string V_ChatRoom_Details {
            get {
                return ResourceManager.GetString("V_ChatRoom_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited Users.
        /// </summary>
        public static string V_ChatRoom_Invited_Users {
            get {
                return ResourceManager.GetString("V_ChatRoom_Invited_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string V_ChatRoom_Name {
            get {
                return ResourceManager.GetString("V_ChatRoom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string V_ChatRoom_Private {
            get {
                return ResourceManager.GetString("V_ChatRoom_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string V_ChatRoom_Public {
            get {
                return ResourceManager.GetString("V_ChatRoom_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string V_ChatRoom_Target {
            get {
                return ResourceManager.GetString("V_ChatRoom_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string V_Enter {
            get {
                return ResourceManager.GetString("V_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string V_Hide {
            get {
                return ResourceManager.GetString("V_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string V_Next {
            get {
                return ResourceManager.GetString("V_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string V_None {
            get {
                return ResourceManager.GetString("V_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not registered?.
        /// </summary>
        public static string V_Not_Registered {
            get {
                return ResourceManager.GetString("V_Not_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string V_Password_Reminder {
            get {
                return ResourceManager.GetString("V_Password_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string V_Prev {
            get {
                return ResourceManager.GetString("V_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string V_Register {
            get {
                return ResourceManager.GetString("V_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string V_Save {
            get {
                return ResourceManager.GetString("V_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string V_Set {
            get {
                return ResourceManager.GetString("V_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string V_Show {
            get {
                return ResourceManager.GetString("V_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} to {1} of {2}.
        /// </summary>
        public static string V_Showing_XtoY_OfZ {
            get {
                return ResourceManager.GetString("V_Showing_XtoY_OfZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Context.
        /// </summary>
        public static string V_Switch_Context {
            get {
                return ResourceManager.GetString("V_Switch_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to admin context..
        /// </summary>
        public static string V_Switch_Context_Admin_Tooltip {
            get {
                return ResourceManager.GetString("V_Switch_Context_Admin_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string V_Until {
            get {
                return ResourceManager.GetString("V_Until", resourceCulture);
            }
        }
    }
}
