//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Contract {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contract() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Contract", typeof(Contract).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a valid admin user to create contract..
        /// </summary>
        public static string Error_Admin_UserId_Rq {
            get {
                return ResourceManager.GetString("Error_Admin_UserId_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all required form data!.
        /// </summary>
        public static string Error_Form_Data {
            get {
                return ResourceManager.GetString("Error_Form_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form is required.
        /// </summary>
        public static string Error_Form_Req {
            get {
                return ResourceManager.GetString("Error_Form_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a user to proceed..
        /// </summary>
        public static string Error_Select_User {
            get {
                return ResourceManager.GetString("Error_Select_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid user for template creation..
        /// </summary>
        public static string Error_Template_Creator_Rq {
            get {
                return ResourceManager.GetString("Error_Template_Creator_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a form for a template..
        /// </summary>
        public static string Error_Template_Form_Rq {
            get {
                return ResourceManager.GetString("Error_Template_Form_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name is required..
        /// </summary>
        public static string Error_Template_Name_Rq {
            get {
                return ResourceManager.GetString("Error_Template_Name_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no template has been found..
        /// </summary>
        public static string Error_Template_Not_Found {
            get {
                return ResourceManager.GetString("Error_Template_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a template before proceeding..
        /// </summary>
        public static string Error_Template_Not_Selected {
            get {
                return ResourceManager.GetString("Error_Template_Not_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is required..
        /// </summary>
        public static string Error_Template_Rq {
            get {
                return ResourceManager.GetString("Error_Template_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is required..
        /// </summary>
        public static string Error_User_Req {
            get {
                return ResourceManager.GetString("Error_User_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Edit .
        /// </summary>
        public static string V_Contract_Edit {
            get {
                return ResourceManager.GetString("V_Contract_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Management.
        /// </summary>
        public static string V_Contract_Management {
            get {
                return ResourceManager.GetString("V_Contract_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Management (Select user).
        /// </summary>
        public static string V_Contract_Management_SelUser {
            get {
                return ResourceManager.GetString("V_Contract_Management_SelUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract details saved successfully!.
        /// </summary>
        public static string V_Contract_Saved {
            get {
                return ResourceManager.GetString("V_Contract_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Form.
        /// </summary>
        public static string V_Create_Form {
            get {
                return ResourceManager.GetString("V_Create_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Template.
        /// </summary>
        public static string V_Create_Template {
            get {
                return ResourceManager.GetString("V_Create_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created .
        /// </summary>
        public static string V_Created {
            get {
                return ResourceManager.GetString("V_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string V_Created_By {
            get {
                return ResourceManager.GetString("V_Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string V_Description {
            get {
                return ResourceManager.GetString("V_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        public static string V_Edit_Template {
            get {
                return ResourceManager.GetString("V_Edit_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string V_Form {
            get {
                return ResourceManager.GetString("V_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated.
        /// </summary>
        public static string V_Last_Updated {
            get {
                return ResourceManager.GetString("V_Last_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        public static string V_Last_Updated_By {
            get {
                return ResourceManager.GetString("V_Last_Updated_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Form.
        /// </summary>
        public static string V_New_Form {
            get {
                return ResourceManager.GetString("V_New_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Contract.
        /// </summary>
        public static string V_Publish {
            get {
                return ResourceManager.GetString("V_Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you publish this contract then the user will be able to view its details..
        /// </summary>
        public static string V_Publish_Info {
            get {
                return ResourceManager.GetString("V_Publish_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Contract.
        /// </summary>
        public static string V_Save_Contract {
            get {
                return ResourceManager.GetString("V_Save_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Template.
        /// </summary>
        public static string V_Save_Template {
            get {
                return ResourceManager.GetString("V_Save_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string V_Submit {
            get {
                return ResourceManager.GetString("V_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Create.
        /// </summary>
        public static string V_Template_Create {
            get {
                return ResourceManager.GetString("V_Template_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Details.
        /// </summary>
        public static string V_Template_Details {
            get {
                return ResourceManager.GetString("V_Template_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A contract template is a form that needs to be filled by an admin user. The employee can only see a completed form as his/her contract once the template has been attached to the contract. &lt;br/&gt;If you want to attach an existing form to your contract as template, please go back to the contract and select an existing form template then attach it accordingly.&lt;br/&gt; Click on the button below to open the form editor and create your form. This will launch a popup window..
        /// </summary>
        public static string V_Template_Details_Intro {
            get {
                return ResourceManager.GetString("V_Template_Details_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Id.
        /// </summary>
        public static string V_Template_Id {
            get {
                return ResourceManager.GetString("V_Template_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string V_Template_Name {
            get {
                return ResourceManager.GetString("V_Template_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Contract.
        /// </summary>
        public static string V_User_Contract {
            get {
                return ResourceManager.GetString("V_User_Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string V_User_Name {
            get {
                return ResourceManager.GetString("V_User_Name", resourceCulture);
            }
        }
    }
}
