//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Document {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Document() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Document", typeof(Document).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not create document!.
        /// </summary>
        public static string Error_Could_Not_Create_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Create_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not update document!.
        /// </summary>
        public static string Error_Could_Not_Update_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Update_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not upload file!.
        /// </summary>
        public static string Error_Could_Not_Upload_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Upload_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator is required.
        /// </summary>
        public static string Error_CreatorIsRequried_Rq {
            get {
                return ResourceManager.GetString("Error_CreatorIsRequried_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is required.
        /// </summary>
        public static string Error_DisplayName_Rq {
            get {
                return ResourceManager.GetString("Error_DisplayName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only file of type:.
        /// </summary>
        public static string Error_File_Type {
            get {
                return ResourceManager.GetString("Error_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required.
        /// </summary>
        public static string Error_FileIsRequried_Rq {
            get {
                return ResourceManager.GetString("Error_FileIsRequried_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry couldn&apos;t retrieve document details..
        /// </summary>
        public static string Error_No_Doc_Details {
            get {
                return ResourceManager.GetString("Error_No_Doc_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no folder or document to view..
        /// </summary>
        public static string Error_No_Folder {
            get {
                return ResourceManager.GetString("Error_No_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any department..
        /// </summary>
        public static string Error_NoDept_ForPermission {
            get {
                return ResourceManager.GetString("Error_NoDept_ForPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any user..
        /// </summary>
        public static string Error_NoUser_ForPermission {
            get {
                return ResourceManager.GetString("Error_NoUser_ForPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file name is required..
        /// </summary>
        public static string Error_OriginalFileName_Rq {
            get {
                return ResourceManager.GetString("Error_OriginalFileName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Your file.
        /// </summary>
        public static string Error_Upload_File {
            get {
                return ResourceManager.GetString("Error_Upload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string TH_Created {
            get {
                return ResourceManager.GetString("TH_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string TH_CreatedBy {
            get {
                return ResourceManager.GetString("TH_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TH_Details {
            get {
                return ResourceManager.GetString("TH_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        public static string TH_DisplayName {
            get {
                return ResourceManager.GetString("TH_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string TH_Downloads {
            get {
                return ResourceManager.GetString("TH_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string TH_Permissions {
            get {
                return ResourceManager.GetString("TH_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string TH_Views {
            get {
                return ResourceManager.GetString("TH_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string V_Add_Folder {
            get {
                return ResourceManager.GetString("V_Add_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string V_Archive {
            get {
                return ResourceManager.GetString("V_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string V_Back_To_List {
            get {
                return ResourceManager.GetString("V_Back_To_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string V_Create {
            get {
                return ResourceManager.GetString("V_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new document.
        /// </summary>
        public static string V_Create_New {
            get {
                return ResourceManager.GetString("V_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string V_Create_New_Folder {
            get {
                return ResourceManager.GetString("V_Create_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string V_Delete {
            get {
                return ResourceManager.GetString("V_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string V_Details {
            get {
                return ResourceManager.GetString("V_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        public static string V_DisplayName {
            get {
                return ResourceManager.GetString("V_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Edit.
        /// </summary>
        public static string V_Doc_Edit {
            get {
                return ResourceManager.GetString("V_Doc_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document details.
        /// </summary>
        public static string V_Document_Details_Title {
            get {
                return ResourceManager.GetString("V_Document_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Documents and Folders.
        /// </summary>
        public static string V_Document_title {
            get {
                return ResourceManager.GetString("V_Document_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string V_Download {
            get {
                return ResourceManager.GetString("V_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string V_Edit {
            get {
                return ResourceManager.GetString("V_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string v_File {
            get {
                return ResourceManager.GetString("v_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string V_Folder {
            get {
                return ResourceManager.GetString("V_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        public static string V_Folder_Make_Public {
            get {
                return ResourceManager.GetString("V_Folder_Make_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string V_Id {
            get {
                return ResourceManager.GetString("V_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string V_New_Folder {
            get {
                return ResourceManager.GetString("V_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document(s) With No Folder.
        /// </summary>
        public static string V_No_Folder {
            get {
                return ResourceManager.GetString("V_No_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole company.
        /// </summary>
        public static string V_Permission_Company {
            get {
                return ResourceManager.GetString("V_Permission_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string V_Permission_Private {
            get {
                return ResourceManager.GetString("V_Permission_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string V_Save {
            get {
                return ResourceManager.GetString("V_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string v_Select {
            get {
                return ResourceManager.GetString("v_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        public static string V_Select_Department {
            get {
                return ResourceManager.GetString("V_Select_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        public static string V_Select_User {
            get {
                return ResourceManager.GetString("V_Select_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string V_Upload {
            get {
                return ResourceManager.GetString("V_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string V_View {
            get {
                return ResourceManager.GetString("V_View", resourceCulture);
            }
        }
    }
}
