//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Document {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Document() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Document", typeof(Document).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot edit somebody else&apos;s document!.
        /// </summary>
        public static string Error_Cant_Edit_Others_Doc {
            get {
                return ResourceManager.GetString("Error_Cant_Edit_Others_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not create document!.
        /// </summary>
        public static string Error_Could_Not_Create_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Create_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not update document!.
        /// </summary>
        public static string Error_Could_Not_Update_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Update_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not upload file!.
        /// </summary>
        public static string Error_Could_Not_Upload_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Upload_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator is required.
        /// </summary>
        public static string Error_CreatorIsRequried_Rq {
            get {
                return ResourceManager.GetString("Error_CreatorIsRequried_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is required.
        /// </summary>
        public static string Error_DisplayName_Rq {
            get {
                return ResourceManager.GetString("Error_DisplayName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Id is required.
        /// </summary>
        public static string Error_DocId_Rq {
            get {
                return ResourceManager.GetString("Error_DocId_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only file of type:.
        /// </summary>
        public static string Error_File_Type {
            get {
                return ResourceManager.GetString("Error_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required.
        /// </summary>
        public static string Error_FileIsRequried_Rq {
            get {
                return ResourceManager.GetString("Error_FileIsRequried_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is required.
        /// </summary>
        public static string Error_FileName_Rq {
            get {
                return ResourceManager.GetString("Error_FileName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry couldn&apos;t retrieve document details..
        /// </summary>
        public static string Error_No_Doc_Details {
            get {
                return ResourceManager.GetString("Error_No_Doc_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no folder or document to view..
        /// </summary>
        public static string Error_No_Folder {
            get {
                return ResourceManager.GetString("Error_No_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any department..
        /// </summary>
        public static string Error_NoDept_ForPermission {
            get {
                return ResourceManager.GetString("Error_NoDept_ForPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t selected any user..
        /// </summary>
        public static string Error_NoUser_ForPermission {
            get {
                return ResourceManager.GetString("Error_NoUser_ForPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file name is required..
        /// </summary>
        public static string Error_OriginalFileName_Rq {
            get {
                return ResourceManager.GetString("Error_OriginalFileName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share type is required.
        /// </summary>
        public static string Error_ShareType_Rq {
            get {
                return ResourceManager.GetString("Error_ShareType_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Your file.
        /// </summary>
        public static string Error_Upload_File {
            get {
                return ResourceManager.GetString("Error_Upload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to archive this document? This document will not be accessed by other users if you click ok..
        /// </summary>
        public static string JS_ARE_YOU_SURE_TO_DELETE_DOC {
            get {
                return ResourceManager.GetString("JS_ARE_YOU_SURE_TO_DELETE_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string TH_Created {
            get {
                return ResourceManager.GetString("TH_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string TH_CreatedBy {
            get {
                return ResourceManager.GetString("TH_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TH_Details {
            get {
                return ResourceManager.GetString("TH_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        public static string TH_DisplayName {
            get {
                return ResourceManager.GetString("TH_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string TH_Downloads {
            get {
                return ResourceManager.GetString("TH_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string TH_Permissions {
            get {
                return ResourceManager.GetString("TH_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string TH_Views {
            get {
                return ResourceManager.GetString("TH_Views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Folder.
        /// </summary>
        public static string V_Add_Folder {
            get {
                return ResourceManager.GetString("V_Add_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string V_And {
            get {
                return ResourceManager.GetString("V_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string V_Archive {
            get {
                return ResourceManager.GetString("V_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string V_Attachment {
            get {
                return ResourceManager.GetString("V_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string V_Back_To_List {
            get {
                return ResourceManager.GetString("V_Back_To_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for more details.
        /// </summary>
        public static string V_Click_More_Details {
            get {
                return ResourceManager.GetString("V_Click_More_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Dialog.
        /// </summary>
        public static string V_Close_Dialog {
            get {
                return ResourceManager.GetString("V_Close_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributed by.
        /// </summary>
        public static string V_Contributed_By {
            get {
                return ResourceManager.GetString("V_Contributed_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        public static string V_Contributor {
            get {
                return ResourceManager.GetString("V_Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string V_Create {
            get {
                return ResourceManager.GetString("V_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new document.
        /// </summary>
        public static string V_Create_New {
            get {
                return ResourceManager.GetString("V_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Folder.
        /// </summary>
        public static string V_Create_New_Folder {
            get {
                return ResourceManager.GetString("V_Create_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created After.
        /// </summary>
        public static string V_Created_After {
            get {
                return ResourceManager.GetString("V_Created_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Before.
        /// </summary>
        public static string V_Created_Before {
            get {
                return ResourceManager.GetString("V_Created_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string V_Date {
            get {
                return ResourceManager.GetString("V_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates between.
        /// </summary>
        public static string V_Dates_Between {
            get {
                return ResourceManager.GetString("V_Dates_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string V_Delete {
            get {
                return ResourceManager.GetString("V_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string V_Details {
            get {
                return ResourceManager.GetString("V_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        public static string V_DisplayName {
            get {
                return ResourceManager.GetString("V_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Edit.
        /// </summary>
        public static string V_Doc_Edit {
            get {
                return ResourceManager.GetString("V_Doc_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string V_Doc_Name {
            get {
                return ResourceManager.GetString("V_Doc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document details.
        /// </summary>
        public static string V_Document_Details_Title {
            get {
                return ResourceManager.GetString("V_Document_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Search.
        /// </summary>
        public static string V_Document_Search {
            get {
                return ResourceManager.GetString("V_Document_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Share.
        /// </summary>
        public static string V_Document_Share {
            get {
                return ResourceManager.GetString("V_Document_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Share Complete.
        /// </summary>
        public static string V_Document_Share_Complete {
            get {
                return ResourceManager.GetString("V_Document_Share_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully shared the following document:{0}.
        /// </summary>
        public static string V_Document_Share_Message {
            get {
                return ResourceManager.GetString("V_Document_Share_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Documents and Folders.
        /// </summary>
        public static string V_Document_title {
            get {
                return ResourceManager.GetString("V_Document_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document was sent to {0}.
        /// </summary>
        public static string V_Document_Was_Shared_With {
            get {
                return ResourceManager.GetString("V_Document_Was_Shared_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string V_Download {
            get {
                return ResourceManager.GetString("V_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string V_Edit {
            get {
                return ResourceManager.GetString("V_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string V_Email {
            get {
                return ResourceManager.GetString("V_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string V_End {
            get {
                return ResourceManager.GetString("V_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string v_File {
            get {
                return ResourceManager.GetString("v_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string V_File_Size {
            get {
                return ResourceManager.GetString("V_File_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string V_File_Type {
            get {
                return ResourceManager.GetString("V_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string V_Folder {
            get {
                return ResourceManager.GetString("V_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        public static string V_Folder_Make_Public {
            get {
                return ResourceManager.GetString("V_Folder_Make_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string V_Id {
            get {
                return ResourceManager.GetString("V_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Folder.
        /// </summary>
        public static string V_In_Folder {
            get {
                return ResourceManager.GetString("V_In_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string V_Link {
            get {
                return ResourceManager.GetString("V_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string V_Message {
            get {
                return ResourceManager.GetString("V_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string V_New_Folder {
            get {
                return ResourceManager.GetString("V_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document(s) With No Folder.
        /// </summary>
        public static string V_No_Folder {
            get {
                return ResourceManager.GetString("V_No_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered no search criteria.
        /// </summary>
        public static string V_No_Search_Criteria {
            get {
                return ResourceManager.GetString("V_No_Search_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string V_Open {
            get {
                return ResourceManager.GetString("V_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or Email.
        /// </summary>
        public static string V_Or_Email {
            get {
                return ResourceManager.GetString("V_Or_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole company.
        /// </summary>
        public static string V_Permission_Company {
            get {
                return ResourceManager.GetString("V_Permission_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string V_Permission_Private {
            get {
                return ResourceManager.GetString("V_Permission_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string V_Recipient {
            get {
                return ResourceManager.GetString("V_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string V_Reset {
            get {
                return ResourceManager.GetString("V_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string V_Save {
            get {
                return ResourceManager.GetString("V_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string V_Search {
            get {
                return ResourceManager.GetString("V_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See results below..
        /// </summary>
        public static string V_Search_Result {
            get {
                return ResourceManager.GetString("V_Search_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string v_Select {
            get {
                return ResourceManager.GetString("v_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        public static string V_Select_Department {
            get {
                return ResourceManager.GetString("V_Select_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user.
        /// </summary>
        public static string V_Select_User {
            get {
                return ResourceManager.GetString("V_Select_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string V_Share {
            get {
                return ResourceManager.GetString("V_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share as.
        /// </summary>
        public static string V_Share_As {
            get {
                return ResourceManager.GetString("V_Share_As", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as attachment.
        /// </summary>
        public static string V_Share_Attachment {
            get {
                return ResourceManager.GetString("V_Share_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} shared document with you..
        /// </summary>
        public static string V_Share_Doc_Email_Title {
            get {
                return ResourceManager.GetString("V_Share_Doc_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can share a link to this document or send it as attachment to a user email.&lt;br/&gt; Select a user from list or type in an email address..
        /// </summary>
        public static string V_Share_Intro {
            get {
                return ResourceManager.GetString("V_Share_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as link.
        /// </summary>
        public static string V_Share_Link {
            get {
                return ResourceManager.GetString("V_Share_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string V_Start {
            get {
                return ResourceManager.GetString("V_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string V_Upload {
            get {
                return ResourceManager.GetString("V_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string V_View {
            get {
                return ResourceManager.GetString("V_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Document Name.
        /// </summary>
        public static string V_With_Document_Name {
            get {
                return ResourceManager.GetString("V_With_Document_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With File type.
        /// </summary>
        public static string V_With_File_Type {
            get {
                return ResourceManager.GetString("V_With_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You made a search with the following criteria:.
        /// </summary>
        public static string V_Your_Search {
            get {
                return ResourceManager.GetString("V_Your_Search", resourceCulture);
            }
        }
    }
}
