//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Document {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Document() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Document", typeof(Document).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not create document!.
        /// </summary>
        public static string Error_Could_Not_Create_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Create_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not upload file!.
        /// </summary>
        public static string Error_Could_Not_Upload_Doc {
            get {
                return ResourceManager.GetString("Error_Could_Not_Upload_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator is required.
        /// </summary>
        public static string Error_CreatorIsRequried_Rq {
            get {
                return ResourceManager.GetString("Error_CreatorIsRequried_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name is required.
        /// </summary>
        public static string Error_DisplayName_Rq {
            get {
                return ResourceManager.GetString("Error_DisplayName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only file of type:.
        /// </summary>
        public static string Error_File_Type {
            get {
                return ResourceManager.GetString("Error_File_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is required.
        /// </summary>
        public static string Error_FileIsRequried_Rq {
            get {
                return ResourceManager.GetString("Error_FileIsRequried_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file name is required..
        /// </summary>
        public static string Error_OriginalFileName_Rq {
            get {
                return ResourceManager.GetString("Error_OriginalFileName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Your file.
        /// </summary>
        public static string Error_Upload_File {
            get {
                return ResourceManager.GetString("Error_Upload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string V_Back_To_List {
            get {
                return ResourceManager.GetString("V_Back_To_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string V_Create {
            get {
                return ResourceManager.GetString("V_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new document.
        /// </summary>
        public static string V_Create_New {
            get {
                return ResourceManager.GetString("V_Create_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        public static string V_Create_New_Folder {
            get {
                return ResourceManager.GetString("V_Create_New_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplayName.
        /// </summary>
        public static string V_DisplayName {
            get {
                return ResourceManager.GetString("V_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document details.
        /// </summary>
        public static string V_Document_Details_Title {
            get {
                return ResourceManager.GetString("V_Document_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Documents and Folders.
        /// </summary>
        public static string V_Document_title {
            get {
                return ResourceManager.GetString("V_Document_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string v_File {
            get {
                return ResourceManager.GetString("v_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string V_Folder {
            get {
                return ResourceManager.GetString("V_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string V_Id {
            get {
                return ResourceManager.GetString("V_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string V_Upload {
            get {
                return ResourceManager.GetString("V_Upload", resourceCulture);
            }
        }
    }
}
