//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumDescription {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumDescription() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.EnumDescription", typeof(EnumDescription).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily (Mon - Fri).
        /// </summary>
        public static string DailyMonToFri {
            get {
                return ResourceManager.GetString("DailyMonToFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chosen department(s).
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        public static string EveryXTime {
            get {
                return ResourceManager.GetString("EveryXTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string EvtDay {
            get {
                return ResourceManager.GetString("EvtDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string EvtHour {
            get {
                return ResourceManager.GetString("EvtHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string EvtMinute {
            get {
                return ResourceManager.GetString("EvtMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string EvtMonth {
            get {
                return ResourceManager.GetString("EvtMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string EvtWeek {
            get {
                return ResourceManager.GetString("EvtWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly (on chosen dates).
        /// </summary>
        public static string MonthlyOnDates {
            get {
                return ResourceManager.GetString("MonthlyOnDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myself Only (private).
        /// </summary>
        public static string MyselfOnly {
            get {
                return ResourceManager.GetString("MyselfOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On specific date(s).
        /// </summary>
        public static string OnDates {
            get {
                return ResourceManager.GetString("OnDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On &lt;span class=&quot;repDay&quot;&gt;{0}&lt;/span&gt; every week.
        /// </summary>
        public static string OnDayOfTheWeek {
            get {
                return ResourceManager.GetString("OnDayOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string TimeBefore {
            get {
                return ResourceManager.GetString("TimeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected user(s).
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly (on chosen years).
        /// </summary>
        public static string YearlyOnSameDate {
            get {
                return ResourceManager.GetString("YearlyOnSameDate", resourceCulture);
            }
        }
    }
}
