//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldFurtherInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldFurtherInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.FieldFurtherInfo", typeof(FieldFurtherInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The whole of your company will be invited and could see this event..
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event will be repeated every day at the same time from Monday to Friday up to the End Date you select.
        /// </summary>
        public static string DailyMonToFri {
            get {
                return ResourceManager.GetString("DailyMonToFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users from department(s) chosen will be notified and could see this event..
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reminder will come based on frequency specified (e.g. every 1 day before event).
        /// </summary>
        public static string EveryXTime {
            get {
                return ResourceManager.GetString("EveryXTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event will be repeated on the days you select for each month. The start and end time will stay the same..
        /// </summary>
        public static string MonthlyOnDates {
            get {
                return ResourceManager.GetString("MonthlyOnDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event will be private and only you as creator could see it..
        /// </summary>
        public static string MyselfOnly {
            get {
                return ResourceManager.GetString("MyselfOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event will be repeated on the dates you enter at the same time. You will need to enter each date in turn..
        /// </summary>
        public static string OnDates {
            get {
                return ResourceManager.GetString("OnDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event will be repeated this specific day each week until the End Date you have selected..
        /// </summary>
        public static string OnDayOfTheWeek {
            get {
                return ResourceManager.GetString("OnDayOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is reminder time before event. (e.g. 2 hours before).
        /// </summary>
        public static string TimeBefore {
            get {
                return ResourceManager.GetString("TimeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User(s) selected will be notified and could see this event.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to enter each year you want the event to be repeated. For each year entered, the event will be repeated on the same day and time as the original event..
        /// </summary>
        public static string YearlyOnSameDate {
            get {
                return ResourceManager.GetString("YearlyOnSameDate", resourceCulture);
            }
        }
    }
}
