//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileTypeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileTypeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.FileTypeNames", typeof(FileTypeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Word.
        /// </summary>
        public static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Word.
        /// </summary>
        public static string docx {
            get {
                return ResourceManager.GetString("docx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE/GIF.
        /// </summary>
        public static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE/JPG.
        /// </summary>
        public static string jpg {
            get {
                return ResourceManager.GetString("jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG.
        /// </summary>
        public static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODT.
        /// </summary>
        public static string odt {
            get {
                return ResourceManager.GetString("odt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE/PNG.
        /// </summary>
        public static string png {
            get {
                return ResourceManager.GetString("png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Point.
        /// </summary>
        public static string ppt {
            get {
                return ResourceManager.GetString("ppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Point.
        /// </summary>
        public static string pptx {
            get {
                return ResourceManager.GetString("pptx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTF.
        /// </summary>
        public static string rtf {
            get {
                return ResourceManager.GetString("rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE/TIF.
        /// </summary>
        public static string tif {
            get {
                return ResourceManager.GetString("tif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE/TIFF.
        /// </summary>
        public static string tiff {
            get {
                return ResourceManager.GetString("tiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
    }
}
