//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormGenerator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormGenerator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.FormGenerator", typeof(FormGenerator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angular Form Generator.
        /// </summary>
        public static string V_Angular_Form_Header {
            get {
                return ResourceManager.GetString("V_Angular_Form_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Data.
        /// </summary>
        public static string V_Form_Data {
            get {
                return ResourceManager.GetString("V_Form_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please edit your form by adding fields and save it..
        /// </summary>
        public static string V_Form_Intro {
            get {
                return ResourceManager.GetString("V_Form_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Preview.
        /// </summary>
        public static string V_Form_Preview {
            get {
                return ResourceManager.GetString("V_Form_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Status.
        /// </summary>
        public static string V_Form_Status {
            get {
                return ResourceManager.GetString("V_Form_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Editor for TotalHR.
        /// </summary>
        public static string V_Form_Title {
            get {
                return ResourceManager.GetString("V_Form_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string V_Invalid {
            get {
                return ResourceManager.GetString("V_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used for TotalHR..
        /// </summary>
        public static string V_Used_By_TotalHR {
            get {
                return ResourceManager.GetString("V_Used_By_TotalHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid.
        /// </summary>
        public static string V_Valid {
            get {
                return ResourceManager.GetString("V_Valid", resourceCulture);
            }
        }
    }
}
