//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.FormMessages", typeof(FormMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tender.
        /// </summary>
        public static string btn_CreateTender {
            get {
                return ResourceManager.GetString("btn_CreateTender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string btn_Register {
            get {
                return ResourceManager.GetString("btn_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string btn_Reset {
            get {
                return ResourceManager.GetString("btn_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string btn_Search {
            get {
                return ResourceManager.GetString("btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btn_value_Continue {
            get {
                return ResourceManager.GetString("btn_value_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Value_Save {
            get {
                return ResourceManager.GetString("btn_Value_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Line of address is required.
        /// </summary>
        public static string Error_Addres1_Rq {
            get {
                return ResourceManager.GetString("Error_Addres1_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 too long (max 255 characters).
        /// </summary>
        public static string Error_Address1_Too_Long {
            get {
                return ResourceManager.GetString("Error_Address1_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 too long (max 255 characters).
        /// </summary>
        public static string Error_Address2_Too_Long {
            get {
                return ResourceManager.GetString("Error_Address2_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 3 too long (max 255 characters).
        /// </summary>
        public static string Error_Address3_Too_Long {
            get {
                return ResourceManager.GetString("Error_Address3_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required.
        /// </summary>
        public static string Error_Amount_Rq {
            get {
                return ResourceManager.GetString("Error_Amount_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Revenu is required.
        /// </summary>
        public static string Error_Annual_Revenue_Rq {
            get {
                return ResourceManager.GetString("Error_Annual_Revenue_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string Error_City_Rq {
            get {
                return ResourceManager.GetString("Error_City_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town or City too long (max 50 characters).
        /// </summary>
        public static string Error_City_Too_Long {
            get {
                return ResourceManager.GetString("Error_City_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some commodities.
        /// </summary>
        public static string Error_Commodities_Rq {
            get {
                return ResourceManager.GetString("Error_Commodities_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company&apos;s name is required.
        /// </summary>
        public static string Error_Company_Name_Rq {
            get {
                return ResourceManager.GetString("Error_Company_Name_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name should not exceed 100 characters.
        /// </summary>
        public static string Error_Company_Name_Too_long {
            get {
                return ResourceManager.GetString("Error_Company_Name_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is required..
        /// </summary>
        public static string Error_CompanyName_Rq {
            get {
                return ResourceManager.GetString("Error_CompanyName_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of employees is required.
        /// </summary>
        public static string Error_CompanyNoEmployees_Rq {
            get {
                return ResourceManager.GetString("Error_CompanyNoEmployees_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type too long (max 50 characters).
        /// </summary>
        public static string Error_CompanyType_Too_Long {
            get {
                return ResourceManager.GetString("Error_CompanyType_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry couldn&apos;t submit form..
        /// </summary>
        public static string Error_Could_Not_Submit_Form {
            get {
                return ResourceManager.GetString("Error_Could_Not_Submit_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country.
        /// </summary>
        public static string Error_Country_Required {
            get {
                return ResourceManager.GetString("Error_Country_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string Error_Description_Rq {
            get {
                return ResourceManager.GetString("Error_Description_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description should not exceed 3000 characters.
        /// </summary>
        public static string Error_Description_Too_long {
            get {
                return ResourceManager.GetString("Error_Description_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already submitted your details..
        /// </summary>
        public static string Error_Duplicate_Registration {
            get {
                return ResourceManager.GetString("Error_Duplicate_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry your email is not registered..
        /// </summary>
        public static string Error_Email_Doesnt_Exist {
            get {
                return ResourceManager.GetString("Error_Email_Doesnt_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email first before using it as username.
        /// </summary>
        public static string Error_Email_Needs_To_Be_Provided {
            get {
                return ResourceManager.GetString("Error_Email_Needs_To_Be_Provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string Error_Email_Reminder {
            get {
                return ResourceManager.GetString("Error_Email_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address too long (max 100 characters).
        /// </summary>
        public static string Error_Email_Too_long {
            get {
                return ResourceManager.GetString("Error_Email_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set a target group for event.
        /// </summary>
        public static string Error_Event_Target_Not_Set {
            get {
                return ResourceManager.GetString("Error_Event_Target_Not_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select attendee(s) for your event.
        /// </summary>
        public static string Error_Event_Target_Required {
            get {
                return ResourceManager.GetString("Error_Event_Target_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a valid logged in user in order to create and event.
        /// </summary>
        public static string Error_Event_UserNotLogged {
            get {
                return ResourceManager.GetString("Error_Event_UserNotLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An end date is required for each event.
        /// </summary>
        public static string Error_EventEndDate_Rq {
            get {
                return ResourceManager.GetString("Error_EventEndDate_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A start date is required for each event.
        /// </summary>
        public static string Error_EventStartDate_Rq {
            get {
                return ResourceManager.GetString("Error_EventStartDate_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A title is required for an event.
        /// </summary>
        public static string Error_EventTitle_Rq {
            get {
                return ResourceManager.GetString("Error_EventTitle_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is requried.
        /// </summary>
        public static string Error_First_Name_Rq {
            get {
                return ResourceManager.GetString("Error_First_Name_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        public static string Error_Firstname_Rq {
            get {
                return ResourceManager.GetString("Error_Firstname_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required.
        /// </summary>
        public static string Error_Gender_Rq {
            get {
                return ResourceManager.GetString("Error_Gender_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date..
        /// </summary>
        public static string Error_Invalid_Date {
            get {
                return ResourceManager.GetString("Error_Invalid_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string Error_Invalid_Email {
            get {
                return ResourceManager.GetString("Error_Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string Error_Last_Name_Rq {
            get {
                return ResourceManager.GetString("Error_Last_Name_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but the details you provided are incorrect..
        /// </summary>
        public static string Error_Login_Failed {
            get {
                return ResourceManager.GetString("Error_Login_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter and select reminder values and frequency as necessary..
        /// </summary>
        public static string Error_Missing_Reminder_Frequency_AndValues {
            get {
                return ResourceManager.GetString("Error_Missing_Reminder_Frequency_AndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a reminder type before continuing..
        /// </summary>
        public static string Error_Missing_Reminder_Type {
            get {
                return ResourceManager.GetString("Error_Missing_Reminder_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone too long (max 30 characters).
        /// </summary>
        public static string Error_MobilePhone_Too_Long {
            get {
                return ResourceManager.GetString("Error_MobilePhone_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have correct profile to create a calendar event.
        /// </summary>
        public static string Error_NoProfile_CreateCalendarEvent {
            get {
                return ResourceManager.GetString("Error_NoProfile_CreateCalendarEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other name too long (max 50 characters).
        /// </summary>
        public static string Error_OtherName_Too_long {
            get {
                return ResourceManager.GetString("Error_OtherName_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title too long (max 30 characters).
        /// </summary>
        public static string Error_OtherTitle_Too_long {
            get {
                return ResourceManager.GetString("Error_OtherTitle_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        public static string Error_Password_Conf_Rq {
            get {
                return ResourceManager.GetString("Error_Password_Conf_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password confirmation doesn&apos;t match the original one..
        /// </summary>
        public static string Error_Password_No_Match {
            get {
                return ResourceManager.GetString("Error_Password_No_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your confirmed password must match the password originally specified.
        /// </summary>
        public static string Error_Password_Not_Matched {
            get {
                return ResourceManager.GetString("Error_Password_Not_Matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between 6 and 15 characters..
        /// </summary>
        public static string Error_Password_NotInRange {
            get {
                return ResourceManager.GetString("Error_Password_NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Error_Password_Rq {
            get {
                return ResourceManager.GetString("Error_Password_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long (max 15 characters).
        /// </summary>
        public static string Error_Password_Too_long {
            get {
                return ResourceManager.GetString("Error_Password_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Password must be between 6 and 15 characters..
        /// </summary>
        public static string Error_PasswordConfirm_NotInRange {
            get {
                return ResourceManager.GetString("Error_PasswordConfirm_NotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Password too long (max 15 characters).
        /// </summary>
        public static string Error_PasswordConfirm_Too_long {
            get {
                return ResourceManager.GetString("Error_PasswordConfirm_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Phone too long (max 30 characters).
        /// </summary>
        public static string Error_PersonalPhone_Too_Long {
            get {
                return ResourceManager.GetString("Error_PersonalPhone_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number too long (max 30 characters).
        /// </summary>
        public static string Error_Phone_Too_Long {
            get {
                return ResourceManager.GetString("Error_Phone_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a contact telephone.
        /// </summary>
        public static string Error_Phone1_Rq {
            get {
                return ResourceManager.GetString("Error_Phone1_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code too long (max 30 characters).
        /// </summary>
        public static string Error_Postcode_Too_Long {
            get {
                return ResourceManager.GetString("Error_Postcode_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a commodity and a location before proceeding.
        /// </summary>
        public static string Error_Quick_Search_Rq {
            get {
                return ResourceManager.GetString("Error_Quick_Search_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered, already exists..
        /// </summary>
        public static string Error_Reg_User_Email_Exists {
            get {
                return ResourceManager.GetString("Error_Reg_User_Email_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select some test territories.
        /// </summary>
        public static string Error_Sales_Territories_Rq {
            get {
                return ResourceManager.GetString("Error_Sales_Territories_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an answer to the secret question.
        /// </summary>
        public static string Error_Secret_Question_Answer_Rq {
            get {
                return ResourceManager.GetString("Error_Secret_Question_Answer_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a secret question.
        /// </summary>
        public static string Error_Secret_Question_Rq {
            get {
                return ResourceManager.GetString("Error_Secret_Question_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a Commodity.
        /// </summary>
        public static string Error_Select_Commodity {
            get {
                return ResourceManager.GetString("Error_Select_Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select a Location.
        /// </summary>
        public static string Error_Select_Location {
            get {
                return ResourceManager.GetString("Error_Select_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry could not save your details..
        /// </summary>
        public static string Error_Sorry_CouldNot_Save_User {
            get {
                return ResourceManager.GetString("Error_Sorry_CouldNot_Save_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be after the end date. Please select correct dates..
        /// </summary>
        public static string Error_StartDate_After_EndDate {
            get {
                return ResourceManager.GetString("Error_StartDate_After_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a start date for event before you add a repeat..
        /// </summary>
        public static string Error_StartDate_Before_Repeat {
            get {
                return ResourceManager.GetString("Error_StartDate_Before_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State or county too long (max 50 characters).
        /// </summary>
        public static string Error_State_Too_Long {
            get {
                return ResourceManager.GetString("Error_State_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname is required.
        /// </summary>
        public static string Error_Surname_Rq {
            get {
                return ResourceManager.GetString("Error_Surname_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAX Id too long (max 50 characters).
        /// </summary>
        public static string Error_TaxtID_Too_Long {
            get {
                return ResourceManager.GetString("Error_TaxtID_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate if you accept our terms of service or not.
        /// </summary>
        public static string Error_Terms_Not_Accepted_Rq {
            get {
                return ResourceManager.GetString("Error_Terms_Not_Accepted_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a title or enter other title..
        /// </summary>
        public static string Error_Title_Rq {
            get {
                return ResourceManager.GetString("Error_Title_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title has a maximum of 150 characters.
        /// </summary>
        public static string Error_Title_Too_Long {
            get {
                return ResourceManager.GetString("Error_Title_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email you entered is already registered..
        /// </summary>
        public static string Error_User_Email_Exist {
            get {
                return ResourceManager.GetString("Error_User_Email_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username you entered is already taken..
        /// </summary>
        public static string Error_User_Name_Exist {
            get {
                return ResourceManager.GetString("Error_User_Name_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        public static string Error_Username_Rq {
            get {
                return ResourceManager.GetString("Error_Username_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name too long (max 100 characters).
        /// </summary>
        public static string Error_UserName_Too_long {
            get {
                return ResourceManager.GetString("Error_UserName_Too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a user type.
        /// </summary>
        public static string Error_UserType_Rq {
            get {
                return ResourceManager.GetString("Error_UserType_Rq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT too long (max 50 characters).
        /// </summary>
        public static string Error_VATID_Too_Long {
            get {
                return ResourceManager.GetString("Error_VATID_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website too long (max 500 characters).
        /// </summary>
        public static string Error_Website_Too_Long {
            get {
                return ResourceManager.GetString("Error_Website_Too_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Info_Months {
            get {
                return ResourceManager.GetString("Info_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Seller Preferences.
        /// </summary>
        public static string Label_Add_Seller_Preferences {
            get {
                return ResourceManager.GetString("Label_Add_Seller_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Attached Files.
        /// </summary>
        public static string Label_AddEdit_Attached_Files {
            get {
                return ResourceManager.GetString("Label_AddEdit_Attached_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Revenue.
        /// </summary>
        public static string Label_Annual_Revenue {
            get {
                return ResourceManager.GetString("Label_Annual_Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached Files.
        /// </summary>
        public static string Label_Attached_File {
            get {
                return ResourceManager.GetString("Label_Attached_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Date.
        /// </summary>
        public static string Label_Award_Date {
            get {
                return ResourceManager.GetString("Label_Award_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid Required.
        /// </summary>
        public static string Label_Bid_Required {
            get {
                return ResourceManager.GetString("Label_Bid_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your business is located in more than one country, please select country where headquarter is..
        /// </summary>
        public static string Label_Business_Country {
            get {
                return ResourceManager.GetString("Label_Business_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Label_City {
            get {
                return ResourceManager.GetString("Label_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodities.
        /// </summary>
        public static string Label_Commodities {
            get {
                return ResourceManager.GetString("Label_Commodities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Information.
        /// </summary>
        public static string Label_Company_Information {
            get {
                return ResourceManager.GetString("Label_Company_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string Label_Company_Name {
            get {
                return ResourceManager.GetString("Label_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string Label_CompanyAddress {
            get {
                return ResourceManager.GetString("Label_CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Email.
        /// </summary>
        public static string Label_CompanyEmail {
            get {
                return ResourceManager.GetString("Label_CompanyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Employees.
        /// </summary>
        public static string Label_CompanyNoOfEmployees {
            get {
                return ResourceManager.GetString("Label_CompanyNoOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Number.
        /// </summary>
        public static string Label_CompanyNumber {
            get {
                return ResourceManager.GetString("Label_CompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        public static string Label_CompanyType {
            get {
                return ResourceManager.GetString("Label_CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Length.
        /// </summary>
        public static string Label_Contract_Length {
            get {
                return ResourceManager.GetString("Label_Contract_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Label_Country {
            get {
                return ResourceManager.GetString("Label_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Label_Department {
            get {
                return ResourceManager.GetString("Label_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Label_Description {
            get {
                return ResourceManager.GetString("Label_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Label_DOB {
            get {
                return ResourceManager.GetString("Label_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUNS Number.
        /// </summary>
        public static string Label_DUNS_Number {
            get {
                return ResourceManager.GetString("Label_DUNS_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Label_End_Date {
            get {
                return ResourceManager.GetString("Label_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string Label_End_Time {
            get {
                return ResourceManager.GetString("Label_End_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter year.
        /// </summary>
        public static string Label_Enter_Year {
            get {
                return ResourceManager.GetString("Label_Enter_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Label_First_Name {
            get {
                return ResourceManager.GetString("Label_First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Label_Gender {
            get {
                return ResourceManager.GetString("Label_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Location(s).
        /// </summary>
        public static string Label_In_Location {
            get {
                return ResourceManager.GetString("Label_In_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries.
        /// </summary>
        public static string Label_Industries {
            get {
                return ResourceManager.GetString("Label_Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Label_Last_Name {
            get {
                return ResourceManager.GetString("Label_Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking For.
        /// </summary>
        public static string Label_Looking_For {
            get {
                return ResourceManager.GetString("Label_Looking_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Label_MiddleName {
            get {
                return ResourceManager.GetString("Label_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Label_Mobile {
            get {
                return ResourceManager.GetString("Label_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Label_Password_Confirm {
            get {
                return ResourceManager.GetString("Label_Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        public static string Label_Phone1 {
            get {
                return ResourceManager.GetString("Label_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        public static string Label_Phone2 {
            get {
                return ResourceManager.GetString("Label_Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Label_PostCode {
            get {
                return ResourceManager.GetString("Label_PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Language.
        /// </summary>
        public static string Label_Pref_Language {
            get {
                return ResourceManager.GetString("Label_Pref_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added.
        /// </summary>
        public static string Label_Reminder_Count {
            get {
                return ResourceManager.GetString("Label_Reminder_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders.
        /// </summary>
        public static string Label_Reminders {
            get {
                return ResourceManager.GetString("Label_Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Label_Repeat {
            get {
                return ResourceManager.GetString("Label_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Deadline.
        /// </summary>
        public static string Label_Response_Deadline {
            get {
                return ResourceManager.GetString("Label_Response_Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Territories.
        /// </summary>
        public static string Label_Sales_Territories {
            get {
                return ResourceManager.GetString("Label_Sales_Territories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Question.
        /// </summary>
        public static string Label_Secret_Question {
            get {
                return ResourceManager.GetString("Label_Secret_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Commodity(s).
        /// </summary>
        public static string Label_Select_Commodity {
            get {
                return ResourceManager.GetString("Label_Select_Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Location(s).
        /// </summary>
        public static string Label_Select_Location {
            get {
                return ResourceManager.GetString("Label_Select_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Preference.
        /// </summary>
        public static string Label_Seller_Preference {
            get {
                return ResourceManager.GetString("Label_Seller_Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Label_Start_Date {
            get {
                return ResourceManager.GetString("Label_Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string Label_Start_Time {
            get {
                return ResourceManager.GetString("Label_Start_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County/State.
        /// </summary>
        public static string Label_State {
            get {
                return ResourceManager.GetString("Label_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendee(s).
        /// </summary>
        public static string Label_TargetGroup {
            get {
                return ResourceManager.GetString("Label_TargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string Label_Tax_Id {
            get {
                return ResourceManager.GetString("Label_Tax_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Information.
        /// </summary>
        public static string Label_User_Information {
            get {
                return ResourceManager.GetString("Label_User_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT ID.
        /// </summary>
        public static string Label_VAT_Id {
            get {
                return ResourceManager.GetString("Label_VAT_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Commodities.
        /// </summary>
        public static string MSG_Add_Commodities {
            get {
                return ResourceManager.GetString("MSG_Add_Commodities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select industries supplied to.
        /// </summary>
        public static string MSG_Add_Industries {
            get {
                return ResourceManager.GetString("MSG_Add_Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Sales Territories.
        /// </summary>
        public static string MSG_Add_Territories {
            get {
                return ResourceManager.GetString("MSG_Add_Territories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the Advanced Search, you can view all suppliers based on the selected Category or commodities of your choice. Please select a category below to start..
        /// </summary>
        public static string MSG_AdvancedSearch_Intro {
            get {
                return ResourceManager.GetString("MSG_AdvancedSearch_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Category.
        /// </summary>
        public static string MSG_Category_Search_Intro {
            get {
                return ResourceManager.GetString("MSG_Category_Search_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select department(s) to invite .
        /// </summary>
        public static string MSG_Departments_Invitee_List {
            get {
                return ResourceManager.GetString("MSG_Departments_Invitee_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your details have been saved successfully!.
        /// </summary>
        public static string MSG_Details_Saved {
            get {
                return ResourceManager.GetString("MSG_Details_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder already added..
        /// </summary>
        public static string MSG_Duplicate_Reminder {
            get {
                return ResourceManager.GetString("MSG_Duplicate_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email and we will send you a reminder for your password.
        /// </summary>
        public static string MSG_Email_Reminder {
            get {
                return ResourceManager.GetString("MSG_Email_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot invite attendees without selecting any!.
        /// </summary>
        public static string MSG_Error_NoAttendee_Chosen {
            get {
                return ResourceManager.GetString("MSG_Error_NoAttendee_Chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree to the Terms of Use and the TotalHR Privacy Statement.
        /// </summary>
        public static string MSG_Terms_Of_Service {
            get {
                return ResourceManager.GetString("MSG_Terms_Of_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user(s) to invite.
        /// </summary>
        public static string MSG_Users_Invitee_List {
            get {
                return ResourceManager.GetString("MSG_Users_Invitee_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string Title_Advanced_Search {
            get {
                return ResourceManager.GetString("Title_Advanced_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Details.
        /// </summary>
        public static string Title_Company_Details {
            get {
                return ResourceManager.GetString("Title_Company_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon Details.
        /// </summary>
        public static string Title_Logon_Details {
            get {
                return ResourceManager.GetString("Title_Logon_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        public static string Title_Personal_Details {
            get {
                return ResourceManager.GetString("Title_Personal_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a reminder.
        /// </summary>
        public static string Toolt_Add_Reminder {
            get {
                return ResourceManager.GetString("Toolt_Add_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete reminder.
        /// </summary>
        public static string Toolt_Delete_Reminder {
            get {
                return ResourceManager.GetString("Toolt_Delete_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit reminder.
        /// </summary>
        public static string Toolt_Edit_Reminder {
            get {
                return ResourceManager.GetString("Toolt_Edit_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string V_Added {
            get {
                return ResourceManager.GetString("V_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use my email as username.
        /// </summary>
        public static string V_Email_As_Username {
            get {
                return ResourceManager.GetString("V_Email_As_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string V_Location {
            get {
                return ResourceManager.GetString("V_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string V_No {
            get {
                return ResourceManager.GetString("V_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None added.
        /// </summary>
        public static string V_None_Added {
            get {
                return ResourceManager.GetString("V_None_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Commodities.
        /// </summary>
        public static string V_Selected_Commodities {
            get {
                return ResourceManager.GetString("V_Selected_Commodities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Location(s).
        /// </summary>
        public static string V_Selected_Locations {
            get {
                return ResourceManager.GetString("V_Selected_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Suppliers.
        /// </summary>
        public static string V_Selected_Suppliers {
            get {
                return ResourceManager.GetString("V_Selected_Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User email as username.
        /// </summary>
        public static string V_User_Email_As_UserName {
            get {
                return ResourceManager.GetString("V_User_Email_As_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string V_Yes {
            get {
                return ResourceManager.GetString("V_Yes", resourceCulture);
            }
        }
    }
}
