//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Gallery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Gallery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Gallery", typeof(Gallery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Photo.
        /// </summary>
        public static string V_Add_Photo_ToAlbum {
            get {
                return ResourceManager.GetString("V_Add_Photo_ToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Details.
        /// </summary>
        public static string V_Album_Details {
            get {
                return ResourceManager.GetString("V_Album_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string V_Album_Name {
            get {
                return ResourceManager.GetString("V_Album_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album View.
        /// </summary>
        public static string V_Album_View {
            get {
                return ResourceManager.GetString("V_Album_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string V_Close {
            get {
                return ResourceManager.GetString("V_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Album.
        /// </summary>
        public static string V_Create_Album {
            get {
                return ResourceManager.GetString("V_Create_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string V_Created_By {
            get {
                return ResourceManager.GetString("V_Created_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string V_Created_On {
            get {
                return ResourceManager.GetString("V_Created_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Picture.
        /// </summary>
        public static string V_Delete {
            get {
                return ResourceManager.GetString("V_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string V_Description {
            get {
                return ResourceManager.GetString("V_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no album found in the database!.
        /// </summary>
        public static string V_Error_No_Album_Found {
            get {
                return ResourceManager.GetString("V_Error_No_Album_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no photo for this album!.
        /// </summary>
        public static string V_Error_No_Photo_For_Album {
            get {
                return ResourceManager.GetString("V_Error_No_Photo_For_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        public static string V_Gallery {
            get {
                return ResourceManager.GetString("V_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Albums.
        /// </summary>
        public static string V_Gallery_Albums {
            get {
                return ResourceManager.GetString("V_Gallery_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery Picture Large.
        /// </summary>
        public static string V_Gallery_Picture_Preview {
            get {
                return ResourceManager.GetString("V_Gallery_Picture_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this picture?.
        /// </summary>
        public static string V_Info_Are_You_Sure_Delete {
            get {
                return ResourceManager.GetString("V_Info_Are_You_Sure_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Albums.
        /// </summary>
        public static string V_List_Of_Albums {
            get {
                return ResourceManager.GetString("V_List_Of_Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string V_No_Photo {
            get {
                return ResourceManager.GetString("V_No_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo deleted successfully!.
        /// </summary>
        public static string V_Photo_Deleted {
            get {
                return ResourceManager.GetString("V_Photo_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but the phot could not be deleted..
        /// </summary>
        public static string V_Photo_Not_Deleted {
            get {
                return ResourceManager.GetString("V_Photo_Not_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Upload.
        /// </summary>
        public static string V_Photo_Upload {
            get {
                return ResourceManager.GetString("V_Photo_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string V_View {
            get {
                return ResourceManager.GetString("V_View", resourceCulture);
            }
        }
    }
}
