//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Payroll {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Payroll() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Payroll", typeof(Payroll).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string V_Account_Name {
            get {
                return ResourceManager.GetString("V_Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string V_Account_Number {
            get {
                return ResourceManager.GetString("V_Account_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Address.
        /// </summary>
        public static string V_Bank_Address {
            get {
                return ResourceManager.GetString("V_Bank_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details.
        /// </summary>
        public static string V_Bank_Details {
            get {
                return ResourceManager.GetString("V_Bank_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string V_Bank_Name {
            get {
                return ResourceManager.GetString("V_Bank_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Ref.
        /// </summary>
        public static string V_Bank_Ref {
            get {
                return ResourceManager.GetString("V_Bank_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        public static string V_Basic_Salary {
            get {
                return ResourceManager.GetString("V_Basic_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string V_Bonus {
            get {
                return ResourceManager.GetString("V_Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Type.
        /// </summary>
        public static string V_Bonus_Type {
            get {
                return ResourceManager.GetString("V_Bonus_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Allowance.
        /// </summary>
        public static string V_Car_Allowance {
            get {
                return ResourceManager.GetString("V_Car_Allowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Pay.
        /// </summary>
        public static string V_Gross_Pay {
            get {
                return ResourceManager.GetString("V_Gross_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Type.
        /// </summary>
        public static string V_Pay_Type {
            get {
                return ResourceManager.GetString("V_Pay_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll.
        /// </summary>
        public static string V_Payroll {
            get {
                return ResourceManager.GetString("V_Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Details.
        /// </summary>
        public static string V_Payroll_Details {
            get {
                return ResourceManager.GetString("V_Payroll_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an Enquiry.
        /// </summary>
        public static string V_Payroll_Enquire {
            get {
                return ResourceManager.GetString("V_Payroll_Enquire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string V_Payroll_Extras {
            get {
                return ResourceManager.GetString("V_Payroll_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Number.
        /// </summary>
        public static string V_Payroll_Number {
            get {
                return ResourceManager.GetString("V_Payroll_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string V_Rate {
            get {
                return ResourceManager.GetString("V_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Breakdown.
        /// </summary>
        public static string V_Salary {
            get {
                return ResourceManager.GetString("V_Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Code.
        /// </summary>
        public static string V_Sort_Code {
            get {
                return ResourceManager.GetString("V_Sort_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NI Number.
        /// </summary>
        public static string V_SS_Number {
            get {
                return ResourceManager.GetString("V_SS_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Reference.
        /// </summary>
        public static string V_Tax_Ref {
            get {
                return ResourceManager.GetString("V_Tax_Ref", resourceCulture);
            }
        }
    }
}
