//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Task {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Task() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.Task", typeof(Task).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Time.
        /// </summary>
        public static string V_Add_Time {
            get {
                return ResourceManager.GetString("V_Add_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned By.
        /// </summary>
        public static string V_Assigned_By {
            get {
                return ResourceManager.GetString("V_Assigned_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned To.
        /// </summary>
        public static string V_Assigned_To {
            get {
                return ResourceManager.GetString("V_Assigned_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to search results.
        /// </summary>
        public static string V_Back_To_Search {
            get {
                return ResourceManager.GetString("V_Back_To_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to task scheduler home.
        /// </summary>
        public static string V_Back_To_Task_Home {
            get {
                return ResourceManager.GetString("V_Back_To_Task_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        public static string V_Create_Task {
            get {
                return ResourceManager.GetString("V_Create_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string V_Department {
            get {
                return ResourceManager.GetString("V_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string V_Description {
            get {
                return ResourceManager.GetString("V_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Recorded.
        /// </summary>
        public static string V_Duration_Recorded {
            get {
                return ResourceManager.GetString("V_Duration_Recorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Record.
        /// </summary>
        public static string V_Edit_Record {
            get {
                return ResourceManager.GetString("V_Edit_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string V_End_Time {
            get {
                return ResourceManager.GetString("V_End_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter search criteria.
        /// </summary>
        public static string V_Enter_Criteria {
            get {
                return ResourceManager.GetString("V_Enter_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of results.
        /// </summary>
        public static string V_No_Of_Results {
            get {
                return ResourceManager.GetString("V_No_Of_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search / Edit Recorded Tasks.
        /// </summary>
        public static string V_Sear_Edit_Record_Task {
            get {
                return ResourceManager.GetString("V_Sear_Edit_Record_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string V_Search {
            get {
                return ResourceManager.GetString("V_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Search Details.
        /// </summary>
        public static string V_Search_Details {
            get {
                return ResourceManager.GetString("V_Search_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Task.
        /// </summary>
        public static string V_Search_Taks {
            get {
                return ResourceManager.GetString("V_Search_Taks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string V_Start_Time {
            get {
                return ResourceManager.GetString("V_Start_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Details.
        /// </summary>
        public static string V_Task_Details {
            get {
                return ResourceManager.GetString("V_Task_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Id.
        /// </summary>
        public static string V_Task_Id {
            get {
                return ResourceManager.GetString("V_Task_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string V_Task_Name {
            get {
                return ResourceManager.GetString("V_Task_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Scheduler.
        /// </summary>
        public static string V_Task_Scheduler {
            get {
                return ResourceManager.GetString("V_Task_Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string V_Task_Scheduler_Options {
            get {
                return ResourceManager.GetString("V_Task_Scheduler_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string V_Task_Search_Result {
            get {
                return ResourceManager.GetString("V_Task_Search_Result", resourceCulture);
            }
        }
    }
}
