//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace totalhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TimeRecording {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TimeRecording() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("totalhr.Resources.TimeRecording", typeof(TimeRecording).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but no time recording found matching your search criteria. Try revising and searching again..
        /// </summary>
        public static string Error_No_Time_Recording {
            get {
                return ResourceManager.GetString("Error_No_Time_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Details.
        /// </summary>
        public static string V_Back_To_Details {
            get {
                return ResourceManager.GetString("V_Back_To_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Options.
        /// </summary>
        public static string V_Back_To_Options {
            get {
                return ResourceManager.GetString("V_Back_To_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Time Recording Home.
        /// </summary>
        public static string V_Back_To_Recording_Home {
            get {
                return ResourceManager.GetString("V_Back_To_Recording_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to task details.
        /// </summary>
        public static string V_Back_To_Task_Details {
            get {
                return ResourceManager.GetString("V_Back_To_Task_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string V_Details {
            get {
                return ResourceManager.GetString("V_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Recorded.
        /// </summary>
        public static string V_Duration_Recorded {
            get {
                return ResourceManager.GetString("V_Duration_Recorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string V_End_Date {
            get {
                return ResourceManager.GetString("V_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string V_End_Time {
            get {
                return ResourceManager.GetString("V_End_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Results to Show.
        /// </summary>
        public static string V_No_Results {
            get {
                return ResourceManager.GetString("V_No_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string V_Options {
            get {
                return ResourceManager.GetString("V_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Time.
        /// </summary>
        public static string V_Record_Time {
            get {
                return ResourceManager.GetString("V_Record_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded By.
        /// </summary>
        public static string V_Recorded_By {
            get {
                return ResourceManager.GetString("V_Recorded_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result Count.
        /// </summary>
        public static string V_Result_Count {
            get {
                return ResourceManager.GetString("V_Result_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string V_Save {
            get {
                return ResourceManager.GetString("V_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string V_Search {
            get {
                return ResourceManager.GetString("V_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string V_Search_Criteria {
            get {
                return ResourceManager.GetString("V_Search_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search/Edit Recorded Time.
        /// </summary>
        public static string V_Search_Edit_Recording {
            get {
                return ResourceManager.GetString("V_Search_Edit_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string V_Search_Result {
            get {
                return ResourceManager.GetString("V_Search_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string V_Start_Date {
            get {
                return ResourceManager.GetString("V_Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string V_Start_Time {
            get {
                return ResourceManager.GetString("V_Start_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string V_Submit {
            get {
                return ResourceManager.GetString("V_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Recording.
        /// </summary>
        public static string V_Time_Recording {
            get {
                return ResourceManager.GetString("V_Time_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording Details.
        /// </summary>
        public static string V_Time_Recording_Details {
            get {
                return ResourceManager.GetString("V_Time_Recording_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Recording For &apos;{0}&apos;.
        /// </summary>
        public static string V_Time_Recording_For_Task {
            get {
                return ResourceManager.GetString("V_Time_Recording_For_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Recording Home.
        /// </summary>
        public static string V_Time_Recording_Home {
            get {
                return ResourceManager.GetString("V_Time_Recording_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeRecording Options.
        /// </summary>
        public static string V_Time_Recording_Options {
            get {
                return ResourceManager.GetString("V_Time_Recording_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Recording Search.
        /// </summary>
        public static string V_Time_Recording_Search {
            get {
                return ResourceManager.GetString("V_Time_Recording_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria.
        /// </summary>
        public static string V_Time_Recording_Search_Criteria {
            get {
                return ResourceManager.GetString("V_Time_Recording_Search_Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        public static string V_UserId {
            get {
                return ResourceManager.GetString("V_UserId", resourceCulture);
            }
        }
    }
}
