CREATE TABLE [dbo].[Company] (
    [ID]                  INT             IDENTITY (1, 1) NOT NULL,
    [Name]                VARCHAR (100)   NOT NULL,
    [Email]               NVARCHAR (100)  NOT NULL,
    [Address1]            VARCHAR (255)   NOT NULL,
    [Address2]            VARCHAR (255)   NULL,
    [Address3]            VARCHAR (255)   NULL,
    [City]                VARCHAR (50)    NULL,
    [StateorCounty]       NVARCHAR (50)   NULL,
    [CountryId]           INT             NULL,
    [Phone1]              VARCHAR (30)    NULL,
    [Phone2]              VARCHAR (30)    NULL,
    [PostCode]            VARCHAR (30)    NULL,
    [CreatedBy]           INT             NOT NULL,
    [CreatedOn]           DATETIME        NOT NULL,
    [LastUpdateBy]        INT             NULL,
    [LastUpdatedOn]       DATETIME        NULL,
    [TaxId]               NVARCHAR (50)   NULL,
    [VATId]               NVARCHAR (50)   NULL,
    [DNUSNumber]          NVARCHAR (50)   NULL,
    [NumberOfEmployees]   INT             CONSTRAINT [DF_Company_NumberOfEmployees] DEFAULT ((1)) NOT NULL,
    [CompanyType]         NVARCHAR (50)   NULL,
    [AnnualRevenue]       DECIMAL (20, 2) NULL,
    [Description]         NVARCHAR (2000) NULL,
    [Website]             NVARCHAR (500)  NULL,
    [PreferredLanguageId] INT             NOT NULL,
    CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED ([ID] ASC)
);

